apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tripla-apps.backendFullname" . }}
  labels:
    {{- include "tripla-apps.backendLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tripla-apps.backendSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tripla-apps.backendLabels" . | nindent 8 }}        
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.port }}
          env:
            - name: PORT
              value: {{ .Values.backend.service.port | quote }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
