apiVersion: v1
kind: Service
metadata:
  name: {{ include "tripla-apps.backendFullname" . }}
  labels:
    {{- include "tripla-apps.backendLabels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: http
  selector:    
    {{- include "tripla-apps.backendSelectorLabels" . | nindent 4 }}
