apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tripla-apps.backendFullname" . }}
  labels:
    {{- include "tripla-apps.backendLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "tripla-apps.backendSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tripla-apps.backendLabels" . | nindent 8 }}        
    spec:
      containers:
        - name: backend
          image: hashicorp/http-echo:latest
          args:
            - "-text=hello"
