apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tripla-apps.frontendFullname" . }}
  labels:
    {{- include "tripla-apps.frontendLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tripla-apps.frontendSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tripla-apps.frontendLabels" . | nindent 8 }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
