apiVersion: v1
kind: Service
metadata:
  name: {{ include "tripla-apps.frontendFullname" . }}
  labels:
    {{- include "tripla-apps.frontendLabels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
  selector:
    {{- include "tripla-apps.frontendSelectorLabels" . | nindent 4 }}
