apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tripla-apps.frontendFullname" . }}
  labels:
    {{- include "tripla-apps.frontendLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "tripla-apps.frontendSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tripla-apps.frontendLabels" . | nindent 8 }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.containerPort }}
          {{- if .Values.frontend.env }}
          env:
          {{- range $key, $value := .Values.frontend.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.livenessProbe.path }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.readinessProbe.path }}
              port: http
          {{- with .Values.frontend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
